# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GerenciadorARADialog
                                 A QGIS plugin
 Este plugin auxilia no gerenciamento de banco de dados de Alvarás Responsáveis Automáticos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-17
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Hiago Cardoso Arquitetura e Urbanismo
        email                : hiagocardoso.arq@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt import QtWidgets
from .ara_manager_dialog_base_ui import Ui_GerenciadorARADialogBase
from .ara_manager_dialog_cadastrar import CadastroARADialog
from .ara_manager_dialog_relatorio import RelatorioARADialog
from . import resources_rc

class TelaPrincipal(QtWidgets.QDialog, Ui_GerenciadorARADialogBase):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

        # Conectando o botão "Cadastrar Processo"
        self.pushButtonCadastrar.clicked.connect(self.abrir_tela_cadastro)
        self.pushButtonRelatorio.clicked.connect(self.abrir_tela_relatorio)

    def abrir_tela_cadastro(self):
        dialog = CadastroARADialog(self)
        dialog.exec_()

    def abrir_tela_relatorio(self):
        dialog = RelatorioARADialog(self)
        dialog.exec_()