# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GerenciadorARADialog
                                 A QGIS plugin
 Este plugin auxilia no gerenciamento de banco de dados de Alvarás Responsáveis Automáticos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-17
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Hiago Cardoso Arquitetura e Urbanismo
        email                : hiagocardoso.arq@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from .ara_manager_dialog_relatorio_ui import Ui_GerenciadorARADialogRelatorio
from . import resources_rc

class RelatorioARADialog(QtWidgets.QDialog, Ui_GerenciadorARADialogRelatorio):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
